# Generated by Django 2.1.2 on 2019-01-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
