# Generated by Django 2.1.2 on 2019-01-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20190123_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frind',
            field=models.ManyToManyField(blank=True, related_name='_user_frind_+', to='Login.User'),
        ),
    ]
