# Generated by Django 2.1.2 on 2019-01-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_user_frind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='frind',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='Login.User'),
        ),
    ]
