# Generated by Django 2.1.2 on 2019-01-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirMessages',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dirname', models.CharField(max_length=100)),
                ('dirpath', models.CharField(max_length=100)),
            ],
        ),
    ]
